#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Scopic_Press Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: Chenla_Scopic_Press_Introduction
  :Name:      /home/deerpig/proj/chenla/projects/press-intro.org
  :Created:   2017-05-15T13:12@Prek Leap (11.642600N-104.919210W)
  :ID:        0cfebbc7-c92c-4bb7-bfb8-6786e0b3eb5d
  :VER:       548100827.577841630
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DXT6-7548
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


 - [[https://medium.com/@nickkokonas/why-we-are-self-publishing-the-aviary-cookbook-lessons-from-the-alinea-book-e89236ab6ca1][Why We Are Self Publishing the Aviary Cookbook - Lessons From the Alinea Book.]]
 - Warehouseing, order fulfillment: [[https://www.blackbox.cool/][Blackbox]]

 - leanpub.com
 - lulu.com

Establish what I'm calling a /Scopic/ press, that publishes works that
capturesand include all of the surrounding context of the main content
being published.

The physical look and feel of published works will be heavily
influenced buy the three volume Plan of St Gall (1979) which is a
large format work with copious references, footnotes and
illustrations.

The primary mission of the Press will be to publish Chenla's
Prologemena and Primer for building and maintaining a distributed
antifragile technological civilization.  The work is designed to
provide patterns, designs, code and core descriptive and proscriptive
texts that will provide a foundation for a) moving from today's
centralized post-industrial civilization, b) rebuilding from after a
collapse and c) building a new civilization from scratch in various
locations on earth and throughout the solar system.

It's expected that the work will take the next 10-20 years to
complete, and will be published in installments with the first
installment printed in 2018 and by 2020 be published on a quarterly
basis until it is complete.  The majority of the work will not be in
print, but will comprise a hypertext and graph-database that is
managed in part by a weak semi-autonomous AI subsystem.

The civilization envisioned aims to be pragmatic, egalitarian and
above all else sustainable economically, culturally, and ecologically.
Rather than proscribing a top-down master-design and plan that is to
be filled in like a child's coloring book, the primer will provide
patterns that can be adapted and combined to set in motion generative
processes that meet sustainable goals over very long time frames.
People don't change much in a lifetime, and societies take many
generations to realize substantive change.  Cities that have been
designed on a city-planner or architect's drafting table are doomed to
failure.  Cities and the infrastructure and buildings and people in
them grow organically over decades and centuries.  What is needed is
an Ent's-eye perspective that can keep long term goals on track over
time frames that span many lifetimes and generations.

The work is meant to be a living document that will changed as new
things are learned and we as individuals, a civilization and a species
learn to adapt to any number of changes that we can't predict or even
imagine today.  But the primer will evolve over time to always address
the needs of the present in context with a history and with an eye
fixed on the future.



* Localizing Globalization

The recent alarm about how robots and automation will eliminate jobs
and only make the rich even richer is a very real scenario.  But it
doesn't have to happen that way.  Automation using AI and robotics is
inevitable, but the form that it takes is not.  Every major
technological revolution results in breaking up existing power
structures and for at least a short time, moves that power from the
center to the edges.  Before power beginds to consolidate around a
small number of players.  We are at the beginning of one of those
moments in history.  What we do with it is up to us.

One of the core ideas that will be introduced in the primer is
/process guilds/.  The idea of decentralizing production and logistics
to make possible a network of production that is far more flexible and
powerful than can be achieved through centralized factorys and supply
chains that are highly efficient at scale.  Robotics and AI will make
it possible for many small operations come work together on a job by
job basis to be able to produce far higher quality goods and services
that are customized for individual needs and when possible to provide
these things as close to where they are needed as possible.  The
system will work a somewhat like bit-torrent, which breaks large files
into smaller parts which are /seeded/ from many different places.  So
that when you download a large file such as a movie, you are not
downloading from one location but many at the same time.  The same
idea could be applied to work as a /thing-torrent/ but instead of each
seeder serving a copy of a part of a file, each seeder will contribute
to the production of a product or service with the last step in being
the delivery of a finished product.  Rather than a single company
placing orders for materials, or sub-assemblies or design or
processing, the network itself will organize it and as each step in
the process guild is bid on and assigned, the network will then create
a torrent that the customer runs and will result in what is needed.

In effect the system takes most of the middlemen out of the picture,
which means that finished goods and services will be far cheaper.
This is exactly what happened with shipping pallets and shipping
containers, they cut out longshoreman and workers who loaded and
unloaded ships, railroad cars and trucks, so that goods could be
transfered from one form of transporation to another in minutes or
hours with a handful of people instead of days and weeks using scores
or even hundreds of people.  When this was combined with computer
networks and global financial transactions over those networks the
result is what we call globalization.  Present day globalization works
best at scale and with moving very large numbers of identical things.
Small producers and small production runs could not scale large enough
to take advantage of the system, so ever larger centralized production
replaced smaller producers.  This is not only true for industrial
production, but for agricultural production as well.

The next stage of globalization will make it possible for small
producers to compete at small scales with companies producing at
scale.  And I believe that there is a window of opportunity to
leverage the strength of small producers to be able to produce highly
customized goods and services that the large centralized producers can
not provide.  If you have a choice between something made locally,
that has been designed and built specifically for you, for the same
price as the cookie cutter product from a factory on the opposite side
of the planet that is designed to break down in three years to force
you to buy another one, which would you choose?

Small local producers who build things that last and are designed to
be repaired and upgraded can be much more than just sell you
something, they are building a relationship with you that might span
decades or even generations.

And nearly every order will assemble a custom supply chain, production
chain and logistics with bids and payments all happening
automatically.

** The end of economies of scale

Economies of scale is the undisputed meta mantra that has been chanted
/ad nauseum/ by every industrialist or industrialist wannabe for the
past hundred years.

Things become increasingly more efficient and cheaper the larger the
scale at which you do them.  No one would argue that.  And this has
been true for a very long time.  But what if it wasn't?

Scale and working at scale is based on some very fundamental
assumptions.  But what if those assumptions were not absolute?  

Oh, you can't compete against Walmart, or Seven-Eleven or McDonalds,
or Alibaba, Amazon, Google, or Facebook because they can buy things in
volume and get their costs down lower than a small shop ever could.
Google can get electricity, bandwidth, and hardware cheaper -- they
have the resources to build datacenters so large that they have their
own the name, the "Googleplex."  Industrial scale farms can keep their
costs so low, and their volumes so high that no one can compete with
them on price.  Small farmers have been driven out of business because
they can't even cover their costs at the prices that the industrial
giants can make a profit at.

