#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Chenla Scopic_Press Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/projects/press-intro.org
:Created:   2017-05-15T13:12@Prek Leap (11.642600N-104.919210W)
:ID:        0cfebbc7-c92c-4bb7-bfb8-6786e0b3eb5d
:VER:       551895146.255538496
:GEO:       48P-491193-1287029-15
:BXID:      proj:NSC2-8582
:Class:     project
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-project-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction


 - [[https://medium.com/@nickkokonas/why-we-are-self-publishing-the-aviary-cookbook-lessons-from-the-alinea-book-e89236ab6ca1][Why We Are Self Publishing the Aviary Cookbook - Lessons From the Alinea Book.]]
 - Warehouseing, order fulfillment: [[https://www.blackbox.cool/][Blackbox]]

 - leanpub.com
 - lulu.com

Establish what I'm calling a /Scopic/ press, that publishes works that
capturesand include all of the surrounding context of the main content
being published.

The physical look and feel of published works will be heavily
influenced buy the three volume Plan of St Gall (1979) which is a
large format work with copious references, footnotes and
illustrations.

The primary mission of the Press will be to publish Chenla's
Prologemena and Primer for building and maintaining a distributed
antifragile technological civilization.  The work is designed to
provide patterns, designs, code and core descriptive and proscriptive
texts that will provide a foundation for a) moving from today's
centralized post-industrial civilization, b) rebuilding from after a
collapse and c) building a new civilization from scratch in various
locations on earth and throughout the solar system.

It's expected that the work will take the next 10-20 years to
complete, and will be published in installments with the first
installment printed in 2018 and by 2020 be published on a quarterly
basis until it is complete.  The majority of the work will not be in
print, but will comprise a hypertext and graph-database that is
managed in part by a weak semi-autonomous AI subsystem.

I could see epub readers growing enormously in power, and if
browsers don't build this into the browser, they could
become as important as the browser.

* ISBN

ISBNs are global ids for manifestations that are doled out
by Bowker for non-trivial fees.  Like it or not they are a
standard in the publishing industry, especially for physical
publications which are not often used for inventory control
by both publishers and book resellers.

 - [[https://www.myidentifiers.com/get-your-isbn-now][Get Your ISBN Now]] | MyIdentifiers.com (Bowker)

#+CAPTION: Bowker Prices for ISBN Blocks (2017)
| Number of ISBNs | Price |
|-----------------+-------|
|          single | $125  |
|              10 | $295  |
|             100 | $575  |
  
Typically publishers now assign ISBNs for:

  - Hardcover
  - Paperback
  - Trade Paperback (if different)
  - ePub
  - Mobi


