#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Scopic_Press Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: Chenla_Scopic_Press_Introduction
  :Name:      /home/deerpig/proj/chenla/projects/press-intro.org
  :Created:   2017-05-15T13:12@Prek Leap (11.642600N-104.919210W)
  :ID:        0cfebbc7-c92c-4bb7-bfb8-6786e0b3eb5d
  :VER:       548100827.577841630
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DXT6-7548
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


 - [[https://medium.com/@nickkokonas/why-we-are-self-publishing-the-aviary-cookbook-lessons-from-the-alinea-book-e89236ab6ca1][Why We Are Self Publishing the Aviary Cookbook - Lessons From the Alinea Book.]]
 - Warehouseing, order fulfillment: [[https://www.blackbox.cool/][Blackbox]]

 - leanpub.com
 - lulu.com

Establish what I'm calling a /Scopic/ press, that publishes works that
capturesand include all of the surrounding context of the main content
being published.

The physical look and feel of published works will be heavily
influenced buy the three volume Plan of St Gall (1979) which is a
large format work with copious references, footnotes and
illustrations.

The primary mission of the Press will be to publish Chenla's
Prologemena and Primer for building and maintaining a distributed
antifragile technological civilization.  The work is designed to
provide patterns, designs, code and core descriptive and proscriptive
texts that will provide a foundation for a) moving from today's
centralized post-industrial civilization, b) rebuilding from after a
collapse and c) building a new civilization from scratch in various
locations on earth and throughout the solar system.

It's expected that the work will take the next 10-20 years to
complete, and will be published in installments with the first
installment printed in 2018 and by 2020 be published on a quarterly
basis until it is complete.  The majority of the work will not be in
print, but will comprise a hypertext and graph-database that is
managed in part by a weak semi-autonomous AI subsystem.

The civilization envisioned aims to be pragmatic, egalitarian and
above all else sustainable economically, culturally, and ecologically.
Rather than proscribing a top-down master-design and plan that is to
be filled in like a child's coloring book, the primer will provide
patterns that can be adapted and combined to set in motion generative
processes that meet sustainable goals over very long time frames.
People don't change much in a lifetime, and societies take many
generations to realize substantive change.  Cities that have been
designed on a city-planner or architect's drafting table are doomed to
failure.  Cities and the infrastructure and buildings and people in
them grow organically over decades and centuries.  What is needed is
an Ent's-eye perspective that can keep long term goals on track over
time frames that span many lifetimes and generations.

The work is meant to be a living document that will changed as new
things are learned and we as individuals, a civilization and a species
learn to adapt to any number of changes that we can't predict or even
imagine today.  But the primer will evolve over time to always address
the needs of the present in context with a history and with an eye
fixed on the future.



---







