#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Women in IT Pilot 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* Women in IT Pilot
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/projects/proj-women-in-it.org
:Created:  2018-05-14T20:13@Prek Leap (11.642600N-104.919210W)
:ID:       6cb90170-68b6-4e5b-9140-14cd61e34aa2
:VER:      579575697.667586081
:GEO:      48P-491193-1287029-15
:BXID:     proj:QOX5-7310
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR
SEE: [[./ww-studyhall-pilot.org][Chalkhall Pilot Program]]

Women have find it challenging to enter the IT industry.
The industry is well known for being male dominated, and is
often hostile to women entering the field.  Employers
generally understand that this is something that has to
change, but there aren't as many women graduating from IT
programs as men, in large part because the hostility to
women is endemic to IT educational programs as well.

In addition to the the challenges that women face in
developed ecconomies, women in developing economies have
additional challenges and responsbilities and expectations
from their families.  The nuclear family is predominant in
developed countries where after finishing school people are
not expected to take as large a role in the day to day life
of their parents and grand parents.  Cambodia is
predominately made up of traditional extended families who
place much of the burden for taking care of 2-3 generations
and earning money for the family.

Cambodian IT education is focused on providing skills in
technologies that are traditionally low paying and
considered to be low skill.  This includes web application
development, low-end mobile application development, and
Windows based middle-ware that is only used in large and
medium sized corporate environments.  The technologies that
are being used by startups the tech giants like Facebook,
Google and Amazon use cutting edge technologies which are
not being taught in Cambodia.  This is holding back foreign
investment in the country because there is no labor pool of
people with the skills that IT companies need to locate in
Cambodia.  This also means that companies which are already
in Cambodia are not able to adopt these new technologies
which would make them competitive with foreign companies
because no one is qualified to support those technologies.

We believe that the solution to these challenges is to teach
the latest technolgies to Cambodian women and take advantage
of the trend towards Remote Work Companies.  There are now a
number of companies that are worth hundreds of millions of
dollars that have hundreds of employees who all work
entirely from wherever they live.  These are progressive
companies who pay market rate or higher salaries and
benifits as any other IT company, but they have no offices.

Our challenge will be to provide women with the skills that
these companies need, place them in these companies, and
provide what Virginia Woolf called, "a room of one's own",
so that Cambodian Remote workers have a place where at or
near home where they can keep flexible hours that allow them
to take care of their families expectations, and provide a
quite, professional place them them to work.

Objectives:

Establish a four year pilot program that will be based at
Prek Leap National College of Agriculture which is located
outside of Phnom Penh.

That will prepare Cambodian women with the knowledge and
skills that will be required for well paying and flexible
jobs for the technologies that will be in most demand at the
time they graduate.  These technologies are where the jobs
are and will be in the next decade throughout the world.

The program is broken into three parts: Communication,
Critical Thinking, Problem Solving and specialization in one
of two fields that are in high demand worldwide; DevOps and
Machine Learning.

The first two years will concentrate on building basic
skills needed before they can begin advanced studies but
will prepare students so that at the end of the first two
years they will be qualified to work as interns, or part
time.

The second two years, students will split their time between
working as a part time remote intern for a foreign or
possibly local IT company.  These will be paid positions,
and the program will place students in companies with the
understanding that while they are working they will be
continuing their studies.  The pilot program will provide
advanced training in either DevOps and Machine-Learning.

At the end of the program they will either be placed in full
time positions at companies they have interned at, or they
will have the option of forming their own Remote work
startup companies either here in Cambodia or abroad.

Currently there are estimated to be 22,000 qualified people
in Machine Learning, and there are are over 125,000 jobs
available in the field at the time this is being written.
Over the next four years the available jobs in AI is
expected to grow to be as high has a million positions
worldwide, but the number of people qualified for these
positions will be less than half of that.

The other specialty is called DevOps, which is a combination
of Software Development, and Systems management and
Operations.  Companies are moving from the traditional
software development practice of developing software in
incremental releases that are periodically rolled out to
customers to what is known as continious development.
Software is developed and deployed as soon as a fix or
feature is complete.  Some companies deploy changes to
production systems as much as 20 or more times every day.
To do this a new job category has emerged, DevOps which
works to coordinate between development teams, and
operations teams, management and customers.  DevOps
positions require interdisciplinary skills that combine
software development and systems administration.  There are
far more DevOps positions available than can be filled, and
demand for these skills is expected to grow dramatically
over the next 10 years.

First Two Year Curriculum Outline:

  - Communications:
    - Technical English; Conversation, Reading, Writing
  - Learning How To Learn:
    - Critical Thinking
    - Introduction to Logic
    - Algorithms
    - Statistics
    - Mathematics for Programers
    - Search & Research Methodologies
  - Practicum 
    - Linux Operating System
    - Introduction to Programing
    - Introduction to System Administration,
    - Introduction to the Web Stack
    - Programing II: Python, Ruby, R, Rust, Go
    - Introduction to Machine Learning & Neural Networks

Status and Pilot Program

A number of Remote Work companies have been approached with
the concept and they are all open to participating in the
program and are enthusiastic about the prospect of being
able to hire qualified women in their companies.

We will ask these companies to sponsor individual students,
and provide tuition, a laptop and female mentors from their
companies who will work with sponsored students during the
first two years of the program.  If the student completes
the program, the sponsor will have the option of taking on
that student as an intern for the second two years of the
program. 

We are in the initial stages of developing the materials for
the curriculum for the first two years.

The program will use a system called /blended/ learning
which records lectures as a series of ten minute long videos
which students watch outside of class, as well as read
course materials.  When they come to class, instructors and
volunteers who will be largely made up of IT professionals
who are visiting Cambodia for a couple of weeks or months,
to spend some of their time working with students one-on-one
in class to practice what they have learned in the videos
and other material.  Blended learning has been a highly
successful method of teaching that gives students access to
teachers when they are actually what would be considered
homework instead of sitting and listening to a lecture.

We intend to finish the base curriculum for the first year
and begin our first pilot class in the semester starting in
October of 2018 with about 15 students.  We will create a
new class every year and expand the program when it is
appropriate. 

All course material will be released under Open Source
Licences and the entire curriculum will be  designed to
be used as a template that can be used to establish other
programs around the world.

We are seeking funds to continue to develop course
materials, produce videos, establish formal agreements with
participating companies and recruit online mentors and
visiting volunteers and coordinate when they come to
Cambodia and how they will work with students.
** References


