#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Subterranean Cooling
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/proj-earth-cooling-tube.org
  :Created: 2017-04-07T10:03@Prek Leap (11.642600N-104.919210W)
  :ID: 57aa26c7-41c0-4cbc-bd32-1059e248b407
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

I was told when I was quite young that the ground
temperature is always around 55F less more than 2M deep
everywhere on earth.  This turns out to be very untrue.

The bad news is that in the tropics, air, earth and water temperatures
all achieve an equilibrium.

However, if we can develop a passive means of removing humidity from
humid air before being passed through the evaporative media then we
would have an effective system.



* References

 - [[https://en.wikipedia.org/wiki/Ground-coupled_heat_exchanger][Ground-coupled heat exchanger]] | Wikipedia
 - [[http://www.daviddarling.info/encyclopedia/E/AE_earth_cooling_tube.html][Earth cooling tube]] | encyclopedia of alternate energy
 - [[http://www.builditsolar.com/Projects/Cooling/EarthtubeNotes.htm][Design notes on earth tube cooling]] | builditsolar.com
 - [[bib:bruelisauer2013choosing][Choosing heat sinks for cooling in tropical climates]] | Marcel Bruelisauer
 - [[bib:chow:2011estimation][Estimation of soil temperature profile in Hong Kong from climatic variables]]
 - [[bib:cheng:2012air][Air Dehumidification with the Porous Hydrophobic Wall in Underground Tunnel]]


Bruelisauer, M., Meggers, F. and Leibundgut, H., 2013. Choosing heat
sinks for cooling in tropical climates. Frontiers of Architectural
Research, 2(3), pp.292-300.

Chow, T.T., Long, H., Mok, H.Y. and Li, K.W., 2011. Estimation of soil
temperature profile in Hong Kong from climatic variables. Energy and
Buildings, 43(12), pp.3568-3575.

Cheng, Z.Q., Jiang, H.B. and Li, Y.R., 2012. Air Dehumidification with
the Porous Hydrophobic Wall in Underground Tunnel. In Advanced
Materials Research (Vol. 518, pp. 4409-4412). Trans Tech Publications.
