#   -*- mode: org; fill-column: 60 -*-
#+TITLE:  SNOT (SneakerNet of Things)
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/proj-snot.org
  :Created: 2017-04-06T19:06@Prek Leap (11.642600N-104.919210W)
  :ID: db188486-dec0-4dab-aae6-9937e8313e24
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

The IOT (Internet of Things) has been getting a lot of attention of
late, but it's not where things are going, the way that most people
think.  Most people think of the IOT as smoke detectors, fridges and
thermostats being connected to the Internet, doing things on our
behalf and spewing out information.  That's not a bad description of
what IOT is today, but it is based on assumptions of a lot of other
things that are true today staying true.

First, IOT will be the biggest spewage of information on the Net.
Devices talking to devices and computers in the cloud will dwarf the
number of human interactions with machines.  This too is true, but
it's only just the beginning.  We still assume that supply chains,
manufacturing, payment and logistics stay relatively the same as they
are now.  That is, big companys dominating the entire chain and being
responsible for building millions of identical copies of branded mass
market devices and other goods.

Human innovation has followed a cycle of innovation that when widely
adopted breaks up centralized systems which are slow and no longer
able to meet what is demanded of them.  Power shifts from the center
to the edges -- whatever technology it is, starts at the edges, breaks
up centralized systems and for a while the power moves to the edges as
well.  That works for a while until people figure out how to leverage
the disruptive technology to gain an advantage of others on the edge,
and a few players end up getting larger and larger and move to the
center where they eventually control everything and we are back to a
centralized power structure again.  That is, until the next
innovation comes along to blow them up as well.

We are now at a point of unimaginable centralization.  You can now
almost count on one hand (if your hand is human and has not suffered
the loss of any digits) the number of companies who now control the
vast majority of the Internet.  There are more telcos, but only
because nation states still put a damper on multi-nationals owning
telecommunication infrastructure on the ground.

There is no single /next/ technology that will be responsible for the
next great breakup and scattering to the edges.  Computers and
networking got us to where we are today -- out to the edges, with the
PC revolution that quickly centralized with Microsoft at the center
(and Apple caught between worlds) and then networking, which displaced
Microsoft and led to Google, Amazon, Alibaba, Facebook and an another
handful of players who are not in the golden circle but are still in
the game.  This not not linear, revolutions, like the future, are not
evenly distributed.  Then Apple changed the game, first with the iPod
and then with the iPhone and iPad.  These devices displaced the big
hardware desktop and laptop markets but ended up consolidating around
Apple, Google, Facebook and Samsung without displacing Alibaba or
Amazon from their positions.  Because these new devices were so
advanced and bleeding edge, things didn't completely blow up and move
to the edges, other than allowing several billion new users from
developing countries to join the party.  Big, but so far it has only
centralized things even more.  This is why the PC, Internet and Mobile
Revolutions are all bundled together.

The next bundled revolutions are now within a few years of hitting
similar tipping points, AI and Robotics.  As Kevin Kelly laid out in
his book, /The Inevitable/, there are directions that technology is
taking us that short of very sudden end of the world events, will
happen not matter what else happens.  But the specific form they will
take can not be known.  AI and Robotics could very well end up
effectively being in completely control by the existing big players.
That would be a lousy outcome, but it is certainly possible.

More likely, the pent up energy and frustration that the present
centralization is creating will blow things up again and move
everything to the edges.  If that happens, a lot of very interesting
things could happen quite rapidly.  But we're getting ahead of
ourselves here.  The reason that I believe that things will blow up is
that the centralized power structures we have in place today rely on
something that has not changed much in centuries -- middlemen.  Big
centralized power structures rely on middlemen to stay in power.  Like
an aircraft carrier group -- the carrier can not survive without a
hundred or more smaller ships, submarines, aircraft which all have
their own supply and support infrastructure to keep that carrier afloat.

There have been no end to science fiction stories that show worlds
that are completely controlled by a single government or a handful of
corporations.  But none of these are convincing for the simple reason
that it is all of the supporting players that provide the a buffer
between the mega-organizations and the very messy world they dominate.
Mega-anything does not do complexity.  Complex systems are not
predictable, they are chaotic, they are beyond complete control.  So
any mega-something will hit very real limits on growth when they push
up against complexity barriers.  It's the smaller companies and
networks and support systems that form a disposable beach head that
keeps the mothership humming away and pouring out widgets to the
masses.

It is only when the slow mothership is no longer able to maintain that
beach head, that things fall apart and they are broken up and things
move back to the edges.  It is my belief that this is what we see over
the next 5-10 years.  Google may have built a fucking huge dike, but
they only have so many fingers to stick in all of the cracks that are
forming before they run out of fingers.

* The Middle Man is Doomed

The first computers and robots were and often still are, human.  Add
AI an robotics to a global cloud and network and most of the tasks
that were handled by human computers and robots will vanish.

In most cases, people think of this in terms of specific job
catagories.  Bus, truck and taxi drivers will be replaced by
autonomous vehicles.  Burger flippers in fast food restaurants, and
cashiers in Walmart will be replaced.  The last vestiges of assembly
line jobs, mining and host of other jobs -- gone.  But in most cases
they are computer and robot jobs that are still being done by humans.
It will hurt, but in a generation or so things will adjust.

What no one is talking about is that there is a vast area of other
jobs that people don't think of as being computer or robotic, which
will vanish as well.  These are the middle men and once the blue
collar jobs are gone, so will the jobs that blue collar workers have
been able to move up to.  A carpenter might loose his (since before
Jesus, carpentry as been a male dominated profession) job but if they
are bright and work hard and have a bit of luck he can become a
contractor and move up to a better standard of living.  A
multi-generational clothing retailer who was put out of business by
big box stores might be able to leverage their contacts and skills in
buying and importing textile goods to become an importer/exporter.

But when all is said and done, the entire middle, all of it, are
ultimately little more than computers and robots.  All of that goes
away.  And when it goes away, so do the floatila that keeps the
monster motherships afloat.

The linear lock-step of: supply chain --> production --> logistics -->
consumer could well shatter.

This is not at first obvious, because we have been led to believe that
large companies will always have an advantage because only large
organizations can take advantage of economies of scale.

If you cut out the middle men, and leverage networking, computation,
AI and robots to automate at small scales, and then cut out the middle
men who take a larger cut out of small transactions and logistics than
transactions and logistics at scale then we have a cloud of suppliers
and producers leveraging an automated, distributed (possibly
federated) network that does all the stuff that the middle men used to
do and take their cut in the process and make the small supplier and
producer as cost effective as the mothership, but far more flexible,
and closer to the end user.  Flexible cloud networks, if large enough
can remove all of the competitive advantages of centralized systems.

It remains to be seen if cutting out the middle men will result in
wealth moving to the small suppliers and producers or if other schemes
will emerge to consolidate things in ways that can't be forseen.  But
there is a window to at least, for a while turn the tide and build a
better life for people that will restore at least the chance to build
viable lives for whole families and communities.  None of this is
certain and the rest of this book will outline how this might happen.

This is a starting point, just before a tipping point that will
massively disrupt everything, that we can work towards.  It is up to
us to make the aftermath of the revolution that is starting to be
better than what we've had until now.

* T 

This is a work that has been decades in the making, that I am now so
immersed in that it's hard for me to understand how wide a net I've
cast and how deep a grave I've dug for myself.

To bring everyone up to speed, so that they can determine for
themselves if these ideas have merit or not will take some time.

We will be introducing a whole fruit salad of new terms, including
Fnords, SNOT, Horcruxes & Hoards, Brambles, Topicspaces, & Burrs,
Cascading Rules Sets, Duck & Canary Tests along side many terms that
will be unfamiliar to many including Holons, Level of Detail, Point of
View, & Rate of Change, Homoiconography, the medieval Trivium &
Quadrivium, Process Philosophy, Pattern Languages, Living Centers,
Polyculture, Bioregions, Identity & Roles, Shearing & Pace Layers and
the Long Now & Short Here.



* SNOT (SneakerNet of Things)

