#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Fnord
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/proj-fnord.org
  :Created: 2017-03-23T18:58@Prek Leap (11.642600N-104.919210W)
  :ID: 5e84bb05-427b-4056-b225-9ce659018c54
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

The bitcoin block chain is about establishing facts, but a very narrow
type of truth; the assertion that a piece of information has been
transfered between two parties, that constitutes a digital transaction.

But there are many different types of assertions that can not be
determined to be true or not that require a number of different
approaches.  In effect we need a toolbox of different tools that can
be used in different combinations to do this.

Why is this important?  In a word, survival.

We survive as individuals, groups and as a species by observing the
world, making assertions about the world -- determine how likely they
are true or not, and then make decsions based on those assertions.  If
we are right, we survive.  If we make too many mistakes or even get a
single existential assertion wrong -- we die.

Our survival depends on our ability to take in information, make
assertions, determine their likelihood fast enough to stay alive.  We
evolved to be able to do this on the Savannah.  We formed into groups,
to increase the amount of information that could be taken in and
evaluated and then shared that information to increase our chances of
survival.  It worked, but in doing so we generated more information
and complexity that required more assertions and mechanisms for the
group to be able to make collective assessments.

Mankind's history can be written as a chain of innovations that we
have made to increase our ability to collect, assert, evaluate and
share information.  And each time we innovate the more complexity we
generate and then have to innovate again to keep up.  This happened at
a fairly steady slow pace for milennia.  But gradually, we began to
realise that the innovation cycles were growing shorter with each new
innovation.  This is in part because all of these innovations made it
possible for us to live longer and more productive lives, and for
infant mortality to be reduced to no longer being statistically
important to our survival.  The population grew dramatically, but this
was not simply a side effect of all of this innovation, it was needed
in order to have enough people around that could innovate fast enough
to keep up with the ever shorter innovation cycles.  This is what
Alvin Toffler was talking about when saying that the rate of change is
increasing logarithmically.  Simply put, we can not go back to a
simplier past without a corresponding die-off in the population.

This does not mean that population will continue to grow forever as
long as we can keep up with the innovation cycle.  By reducing infant
mortality and educating women we have effectively put the brakes on
out of control population growth.  The United Nations, along with most
of the scientific community see global population continue to grow to
just under 10 billion, followed by a massive shrinking of the
population -- possibly as low as half of today's global population.

In many respects this is good news, but what remains to be seen is how
this will effect the innovation cycle.  Man has managed to use up most
of the easily accessible natural energy and raw material resources.
And we have gone so far beyond the carrying capacity of the planet
without those innovations, that the resulting problems are going to
start rapidly accelerating.  Even if we return to a population that is
half of today's, the damage done to the climate, and the exhaustion of
resources means that the innovation cycle will have to continue to
accelerate for many more generations until the climate can return to
the stability that we have enjoyed over the past hundreds of years.

The problem is that we won't have the population to be able to
innovate as quickly, let alone fast enough to keep ahead of these
problems long enough to get through the next several hundred years.

Clearly, what this means is that we will need to find a way of making
each of member of that smaller, stable population to be orders of
magnitude more cognitively productive than we do now.

There are a number of different ways this can happen, or more
accurately, we will need combination of different things:

  - cognitive surplus :: clay shirky -- need to harness a larger
       percentage of our population to innovate and put the cognitive
       surplus that now is spent on time sinks like Facebook to
       actually do things that improve our ability to survive -- not
       just wallow in a glut of products from the present
       manufacturing surplus.
  - cognitive extension :: AI is about extending our neocortex, AI is
       us and we are AI.
  - extending muscle :: in a nutshell, robotics 
  - expansion :: it will be impossible to do if mankind is confined to
       this planet, we need to become a solar speicies and
       civilization -- innovation requires new places to
       expand into.  That's what the moon, mars and the belt
       are about.  if we don't expand we die, it's that
       simple.  Expansion gives us breathing room, it gives us places
       to let all of the smart AI driven robots to exploit resources
       it allows us to move heavy industry and the pollution that is 
       the driver of climate change to places where it won't matter. 
       Space can't be more toxic and dangerous than it already is.

