#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Library Project 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Library Project
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/projects/proj-library.org
  :Created:   2018-08-04T17:38@Prek Leap (11.642600N-104.919210W)
  :ID:        2b7df7e6-f2d8-4543-ac93-597bc5de24ae
  :VER:       586651164.284407893
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:LAJ7-0251
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:


** From 20th Century Teaching College to 21st Century Research University

PNCA faces a number of challanges as it makes the transition from a
teaching college to a research university of agriculture and
technology.

  - Cultivate policies & a culture where research is an key part
    of teaching.
  - Add new emerging technologies and techniques.
  - Build a solid academic foundation for critical thinking,
    intellectual inquiry and problem solving.

Asking existing staff and departments to add new technologies is not
easy.  The changes in the past 10 years in science and technology have
not been steady incremental change.  Whole new disciplines are
emerging that didn't exist 15 years ago.  Robotics, Artifical
Intelligence, Complexity, Probability and Graph Theories, Satellite
Positioning, Imaging and Mapping, 3D scanning, computer controlled
routers, printers and laser cutters, Cloud Computing, Genetic Editing,
Behavioral Economics and Big Data are just a few of the technologies
that are transforming all parts of life and work.  Understanding what
these technologies are and how to use them will be critical to anyone
entering the job market over the next decade.

The Chenla Institute proposes to help the school bridge this gap, by
creating pilot programs that will develop new course material,
projects and research in many of these fields.  The pilot programs
will work with departments to develop new courses, prepare and train
teachers, build and set up the infrastructure needed to use them.
Once the pilot course is finished, and the department is comfortable
with the material, the course will move into that department.

We can also provide cross-disciplinary services that can be used by
all departments.  In particular we see four core services:

  - IT Cloud Computing, Storage and Online Courseware.
  - A Permanent Media Lab for production of multimedia for use by
    departments.
  - A digital library system that will include a digital catalog, a
    digitization lab for converting paper and other media into
    electronic formats and an electronic library catalog system for
    both students and staff that is connected to scientific,
    agricultural and other technical papers, books and data from
    around the world.
  - A Fabrication Lab (or Fab Lab) that provides a workshop for
    working with wood and metal as well as computer controlled
    routers, laser cutters, 3D printers etc.

These services can then be combined to create projects that would
otherwise be impossible to do at the school.  For example:

*GRASS LAB* Create an inexpensive production chain for turning bamboo
into a wide variety of products.  Set up a bamboo treatment system
using borax salt and chili pepper.  Process bamboo poles into "sticks"
which are then glued together and pressed to create bamboo plywood.
The bamboo plywood is then cut using a computer controlled CNC router
to create furniture (SEE OpenDesk) and even whole buildings (SEE
OpenHouse) from 3D models.

*BIG HISTORY* Develop a two semester foundation-year class that
provides students with a mental framework that ties together
everything they will learn over the next four years of study.  It's
important that students understand how what they learn in school fits
into the big picture of how the world works and how everything is
related to everything else.  It is important that students can tie
themselves, their career, family, culture and history together.

Big History focuses on developing information literacy, understanding
how to find, evaluate and use information critically and the
fundemental concepts and skills needed to do research by teaching a
history of the universe that starts with the Big Bang and ends at the
present day.  Big History is now taught around the world in more than
twenty countries both at the High School and University level and is
supported by the Bill Gates Foundation.

*DOORSTEP* Develop a framework for small holding farmers to
intensively develop the immediate area around their house for the
production of a wide variety of food, improve the quality of rural and
poor housing (using techniques developed by GRASS LAB) and leverage
cloud computing and artificial intelligence networks to coordinate and
make it possible for small businesses and farmers to do more local
processing of agricultural products that can be aggregated using the
network and 


** b>i Research
  

  |-------------+-----------------------------------------------------------|
  | Fab Lab     | Fabrication-Maker Laboratory-Workshop                     |
  | Digi Lab    | Digital Libraries                                         |
  | Robo Lab    | Robotics; drones, industrial, agricultural                |
  | Media Lab   | Digitization, Video Production, 3D models, Motion Capture |
  | Viz Lab     | GPS, Mapping, Satellite Imaging & Processing              |
  |-------------+-----------------------------------------------------------|
  | Big History | Info Literacy, Critical Thinking, Science as History      |
  |-------------+-----------------------------------------------------------|
  | Grass Lab   | Bamboo Industrial Supply & Production Chain               |
  |-------------+-----------------------------------------------------------|

** Library Project


BMF was originally meant to be a platform for creating very long term
digital library collections.

We propose to build an prototype electronic library system for PNCA
which will serve as a pilot for all school, public and national
archives and libraries.

The goals are as follows:

Establsh a digitization system for all forms of recorded media
including books, photos, artwork (both visual 2D and 3D art such as
stone sculptures) audio and video recordings.

A digital cataloging system that is compatible and interoperable with
the Dewy Decimile System, MARC (Library of Congress), The British
Library Catalog, The Bliss Catalog system and World Cat.

An achival system to ensure that digital holdings are not lost. This
will be made up of three parts:

  1. A real-time storage system for people to download items in
     popular formats such as PDF, HTML (epub & mobi ebook).
  2. A near-line storage system that will keep multiple copies in
     different locations using a MAID (massive array of idle disks)
     that can provide backups and copies of items which are seldom
     accessed for decades.
  3. An off-line long term archival system that can store items for
     centuries or longer without any cost to store other than
     maintaining a safe place for them to be kept.

We will partner with the "Arch Mission Foundation" who is actively
developing and testing a variety of very long-term archival storage
technologies including:

  - 5D laser optical data storage in quartz
  - Nickel ion-beam atomic scale storage
  - Molecular storage on DNA molecules
  - Durable space-based flash drive storage
  - Long duration DVD disk technology
  - Quantum information storage

Our pilot program will test at least three different technologies to
determine which is most suitible for use by Cambodian libraries and
archives.

For more information, see:

  -  https://medium.com/arch-mission-foundation/arch-mission-foundation-announces-our-payload-on-spacex-falcon-heavy-c4c9908d5dd1
  -  https://www.archmission.com

The software system will employ what is called "semantic storage"
which preserves the surrounding context of everything in the system.
This ensures that people will be able to understand what is stored in
the collections for centuries.  For example, if legal records are
stored, a record of every person, place, or event that is mentioned in
a document will have a record explaining the who, what, where and when
behind everything in the library.

The system will employ block-chain technology and when required.
cryptography to ensure that all copies are intact and haven't been
tampered with.  If some items are meant to be sealed for a specific
period of time before they are released, keys can be designed that
will only be able to decrypt the contents after that period of time as
passed.

The pilot program will draft several whitepapers as a first step
towards developing a national library strategy for Cambodia for the
21st Century.  This will include functional requirements, the
proof-of-concept pilot program software, a fifty year roadmap and
recommendations for legislation that will been needed for Cambodia to
modernize its library system to the same level as developed countries.

The pilot program will establish a digitalization system and digital
library on campus at Prek Leap National College of Agriculture, and
convert existing items in the library into digital formats.  After the
initial system is working, the pilot program will be expanded to
include other universities and invite the Cambodian National Library to
participate.

The first stage of work is expected to take 2-4 years and largely be
staffed by volunteers and students interested in studying library and
archival science.  The initial digitization system will focus on book,
photo and art scanning using book scanners that will be built from
open source plans and inexpensive parts.

---

teach library, search and information literacy


