#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Egg Mobile
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/proj-egg-mobile.org
  :Created: 2017-03-20T14:36@Prek Leap (11.642600N-104.919210W)
  :ID: 81eacc8c-d818-4b4d-940a-fc3d10ed9fd7
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Based on Joel Salatin's Egg Mobile.

 - [[https://en.wikipedia.org/wiki/Joel_Salatin][Joel Salatin]] | Wikipedia
 - [[http://permaculturenews.org/2010/09/03/how-to-make-an-egg-mobile/][How to Make an Egg Mobile]] | The Permaculture Research Institute
 - [[https://www.milkwood.net/2013/01/03/enter-the-egg-mobile-start-with-what-youve-got/][Enter the egg mobile (start with what you've got)]] | Milkwood
 - [[http://www.polyfacefarms.com/2011/07/25/pastured-eggs/][Pastured Eggs]] | Polyface, Inc.

Our version must have very good air-flow and shading/and rain shelter.

  - clean (hose clean)
  - cool
  - dry (during rainy season)

I tend to think we will need a double-roof -- perhaps a vinyl top roof
and a metal/thatch sub-roof?


 - [[http://www.nortoncreekpress.com/wordpress/poultry/fresh_air_poultry_houses_a/fresh-air-poultry-houses-sample-chapter/][Fresh Air Poultry Houses Sample Chapter]] | Norton Creek Press



#+begin_quote
Food and water is made available within the egg-mobile.

The floor is made of 1″x2″ hardware cloth to allow the droppings to
fall out onto the pasture.

Mr. Salatin runs about 100 chickens to clean up after every 100
cows. The chickens will cover about two acres per day of the area
surrounding the egg-mobile.

The chickens typically will not roam for than 200 yards from the
egg-mobile in a day.

However, a set up like this one is best used on larger
acreage. Because the chickens will roam 200 yards, this means that
they will head back to the barn, original coop, garden, etc. on a
smaller plot of land.

The trick is to have the chickens far enough away from their original
home so that they learn to identify the egg-mobile as home.

It is also important to keep them moving so they don’t home in on any
one spot. By moving them every 2 days or so, the flock doesn’t start
laying eggs in the grass.

Fresh pasture also prevents the birds from wandering too far looking
for new forage.

One thing both the movable “coop” and the egg-mobile have in common is
that the benefit only comes when insects are plentiful.

-- [[http://www.chickenkeepingsecrets.com/chicken-coops/what-is-an-egg-mobile/][What Is An “Egg Mobile”?]]
#+end_quote
