#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to Publishing projects
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/projects/publish-intro.org
  :Created:   2017-05-23T18:03@Prek Leap (11.642600N-104.919210W)
  :ID:        6fcd8c24-7ecf-4a97-a5e4-ff7265af9e56
  :VER:       548809468.363406546
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:JDQ0-5773
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


I am so sick of websites -- there is so much crap that vies for one's
attention it's no wonder people complain about being distracted.

I've been looking into EPUB3 today to see what that can do for us, and
I was pleasantly surprised that EPUB is such a powerful, simple, open
format.  The great thing about epub is that it leverages the web stack
without using /web browsers/.  There is more structure than the web,
which is all good to me.  I'm now exploring if it can be used for
large form-factor books -- these wouldn't open on mobile, but that's
not such a bad thing.  The sequential nature of epubs, and that it is
desiged to be paged, not scrolled, is very powerful.

Ah! and it's very attractive that epub is portable -- it can be served
from a server, but it works just as well as a file that can be copied
and pasted as well....  Send the file -- which could include bmf index
and metadata and source and then it can propagate through the network
via something like bit-torrent, and then be indexed and integrated
into your bramble....

In fact, by using the css media, we could even have versions designed
to run in text-based displays like an emacs app...

Looked at [[http://vivliostyle.com/en/][vivliostyle]] and their platform is impressive, but all
proprietary, and sadly CSS Regions has not been adopted by browsers.
In many respects what they are building is a lot of what I would like,
but again it's not open....  non-starter.


