#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to Publishing projects
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/projects/publish-intro.org
  :Created:   2017-05-23T18:03@Prek Leap (11.642600N-104.919210W)
  :ID:        6fcd8c24-7ecf-4a97-a5e4-ff7265af9e56
  :VER:       548809468.363406546
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:JDQ0-5773
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

 - [[https://en.wikipedia.org/wiki/Monograph][Monograph]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Monographic_series][Monographic series]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Festschrift][Festschrift]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Serial_(publishing)#Periodicals][Serial (publishing)]] | Wikipedia
   - [[https://en.wikipedia.org/wiki/Academic_journals][Academic journal]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Reference_work][Reference work]] | Wikipedia

In publishing there are monographs, reference works and
serials.

On the Web there are web pages, blogs, wikis, and posts.

A post is simular to an article that you would see in a
magazine or newspaper.  There are some reference works in
the form of wikis (wikipedia stands out) and there is a
great deal of documentaion in the form of hierarchically
structured texts simular to books.

But the more you look at the web, electronic monographs,
especially book length monographs are the exception.  The
Web is not an electronic library, it is something else.
There is nothing wrong with this but there are institutional
roles that monographs and journals play that the Web is not
meeting.


Organization of journals:

  - Volumes
    - Issue
      - Page 

Page numbering usually starts from the first issue of a
volume to the last issue of a volume.


 original research papers/articles
 review articles
 book reviews

   - selective
   - enumerative (complete, ordered listing of all the items in a collection)
   - evaluative

  - [[https://en.wikipedia.org/wiki/Enumeration][Enumeration]] | Wikipedia

---

dead tree codexes are designed to be distributed -- the web
is the opposite.

a printed book is frozen at publication, and may only change
when a new edition is published.  The web can change
instantly -- but there is no mechanism to ensure past
versions are saved, and because there is often only one copy
of something on the web, on a server that requires hardware,
cooling, electricity and bandwidth to maintain, the web is
highly susceptible to benign neglect -- and there are almost
not institutions that have emerged who are trying to
preserve content independently of the web sublisher
(brewster has done an amazing job, but he is only one, and
remains an anomoly) what is needed is for archive.org to
become a model for a new kind of instition that will do what
libraries have traditionally done -- but archive.org is a
part of the web, and it is a centralized resource in the
same way that what it is archiving is as well.  Using a
centralized system to back up centralized systems is not an
answer.

