#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to Publishing projects
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/projects/publish-intro.org
  :Created:   2017-05-23T18:03@Prek Leap (11.642600N-104.919210W)
  :ID:        6fcd8c24-7ecf-4a97-a5e4-ff7265af9e56
  :VER:       548809468.363406546
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:JDQ0-5773
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

 - [[https://en.wikipedia.org/wiki/Monograph][Monograph]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Monographic_series][Monographic series]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Festschrift][Festschrift]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Serial_(publishing)#Periodicals][Serial (publishing)]] | Wikipedia
   - [[https://en.wikipedia.org/wiki/Academic_journals][Academic journal]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Reference_work][Reference work]] | Wikipedia

 - [[https://www.theguardian.com/higher-education-network/2017/may/25/its-time-for-academics-to-take-back-control-of-research-journals][It's time for academics to take back control of research journals]] | The Guardian
 - [[bib:fyfe:2017untangling][Untangling Academic Publishing]] | Aileen Fyfe (2017) 
 - [[https://zenodo.org/record/546100#.WSmCybMxVph][Untangling Academic Publishing]] | Zenodo

In publishing there are monographs, reference works and
serials.

On the Web there are web pages, blogs, wikis, and posts.

A post is simular to an article that you would see in a
magazine or newspaper.  There are some reference works in
the form of wikis (wikipedia stands out) and there is a
great deal of documentaion in the form of hierarchically
structured texts simular to books.

But the more you look at the web, electronic monographs,
especially book length monographs are the exception.  The
Web is not an electronic library, it is something else.
There is nothing wrong with this but there are institutional
roles that monographs and journals play that the Web is not
meeting.


Organization of journals:

  - Volumes
    - Issue
      - Page 

Page numbering usually starts from the first issue of a
volume to the last issue of a volume.


 original research papers/articles
 review articles
 book reviews

   - selective
   - enumerative (complete, ordered listing of all the items
     in a collection)
   - evaluative

  - [[https://en.wikipedia.org/wiki/Enumeration][Enumeration]] | Wikipedia

---

dead tree codexes are designed to be distributed -- the web
is the opposite.

a printed book is frozen at publication, and may only change
when a new edition is published.  The web can change
instantly -- but there is no mechanism to ensure past
versions are saved, and because there is often only one copy
of something on the web, on a server that requires hardware,
cooling, electricity and bandwidth to maintain, the web is
highly susceptible to benign neglect -- and there are almost
not institutions that have emerged who are trying to
preserve content independently of the web sublisher
(brewster has done an amazing job, but he is only one, and
remains an anomoly) what is needed is for archive.org to
become a model for a new kind of instition that will do what
libraries have traditionally done -- but archive.org is a
part of the web, and it is a centralized resource in the
same way that what it is archiving is as well.  Using a
centralized system to back up centralized systems is not an
answer.

There is also a very important distinction between backups,
which preserves the state of a running system, to an
archive, which preserves the information in that system.

----

Part of the solution could be to get web sites who are
serious about what they are publishing, to create serialized
epubs of their content and copies placed in repositories.
This should be as easy as setting up an RSS feed -- and
should be part of the orginal development of the web site.

-----

It will be important to convince publishers to stop hoarding
older content by placing it behind paywalls.  But we need to
offer them a carrot in return -- to give them another
revenue source to replace it....

----

what about using a blockchain miner approach to creating
trusted indexes -- different people index and run through
duck tests, and when there is a consensus that index is
accepted, and the hash of the index is added to the
blockchain which is becomes part of the epub, that can be
externally verified.

for this to work we will need open source indexing and
ducktest suites that are maintained by a group that is
trusted.

So there is a hash of the original, a trustless index that
also has a hash -- so this reduces the problem of people
trying to game the system.  And it establishes versioned
editions that are consistent in a distributed distribution
network.

----

we then expand this to test the truth of fnords -- that's
what fnord.ltd will do....

and with this all in place we can the add annotations

----

it goes back to what paul graham was saying -- first find a
niche then grow... scholarly publishing is a good place to
start...
