#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Saltmine Server
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/salt-saltmine.org
  :Created: 2017-04-21T13:59@Prek Leap (11.642600N-104.919210W)
  :ID: 2f5ecbe0-148e-49db-a62e-074525a3e25d
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Saltmine is the code name for the BMF Server software which will
include a graph database, indexer, version control system etc.

Saltmine will be embedded in Horcrux containers, which are
self-contained holons that provide, storage, as well as self-index,
self-replication, provide distributed version control (that
didn't come out right), access control etc.

* Docker/Rkt Containers

I realize that horcruxes as proposed aren't single process
containers.  But I don't want to run full blown VMs either.
Containers can certainly run multiple processes -- but although the
horcrux is running multiple processes it will still interface with the
outside world as if it is a single-process container.  At least that's
my idea at the moment -- it remains to be seen if this will work out
as planned.

* Alpine Linux

* Bit Torrent


So why bit torrent instead of something like Whisper or IPFS?

  - [[https://en.wikipedia.org/wiki/InterPlanetary_File_System][InterPlanetary File System]] | Wikipedia
  - [[https://ipfs.io/][IPFS is the Distributed Web]] | Home

IPFS uses a network to provide a function that has
traditionally been provided by institutions which provide
checks and balances and resourses to maintain the survival
of copies  -- the idea is that there will be market
incentives that will ensure content is kept alive.

bit torrent is poor at keeping files available over long
time periods.

I don't think that either approach provides a solution to
benign neglect.


* GT.M

#+begin_comment
Interested in the idea of using GT.M for the aggregate saltmine graph
database...
#+end_comment

  - [[http://www.mgateway.com/docs/universalNoSQL.pdf]["A Universal NoSQL Engine, Using a Tried and Tested
    Technology"]] | Tweed, Rob; James, George (2010) 
  - [[https://en.wikipedia.org/wiki/GT.M][GT.M]] | Wikipedia
  - [[http://www.fisglobal.com/solutions/Banking%20and%20Wealth/Services/Database%20Engine][GT.M Database]] | FIS
  - [[https://sourceforge.net/projects/fis-gtm/][GT.M High end TP database engine download]] | SourceForge.net

  - [[https://github.com/CoherentLogic/lorikeem][CoherentLogic/lorikeem]] | LorikeeM MUMPS Developer Tools for GNU Emacs

#+begin_src sh
sudo apt-get install fis-gtm
#+end_src

* Blockchain

 - [[https://www.igvita.com/2014/05/05/minimum-viable-block-chain/][Minimum Viable Block Chain]] - igvita.com
 - [[http://johnmathews.eu/blockchain-introduction.html][Blockchains from the ground up: Part 1]] | John Mathews
 - [[https://anders.com/blockchain/][Blockchain Demo]] | video
 - [[https://github.com/anders94/blockchain-demo/][anders94/blockchain-demo]] | GitHub


