#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Saltmine Server
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/salt-saltmine.org
  :Created: 2017-04-21T13:59@Prek Leap (11.642600N-104.919210W)
  :ID: 2f5ecbe0-148e-49db-a62e-074525a3e25d
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Saltmine is the code name for the BMF Server software which will
include a graph database, indexer, version control system etc.

Saltmine will be embedded in Horcrux containers, which are
self-contained holons that provide, storage, as well as self-index,
self-replication, provide distributed version control (that
didn't come out right), access control etc.

* Docker/Rkt Containers

I realize that horcruxes as proposed aren't single process
containers.  But I don't want to run full blown VMs either.
Containers can certainly run multiple processes -- but although the
horcrux is running multiple processes it will still interface with the
outside world as if it is a single-process container.  At least that's
my idea at the moment -- it remains to be seen if this will work out
as planned.

* Alpine Linux

 - [[https://www.alpinelinux.org/][Alpine Linux]] | Home
 

#+begin_quote
Alpine Linux is built around musl libc and busybox. This
makes it smaller and more resource efficient than
traditional GNU/Linux distributions. A container requires no
more than 8 MB and a minimal installation to disk requires
around 130 MB of storage. Not only do you get a
fully-fledged Linux environment but a large selection of
packages from the repository.

-- [[https://www.alpinelinux.org/][Alpine Linux]] | Home
#+end_quote

* Bit Torrent

Bit torrent has evolved into a pretty amazing technology and
is proven to work at scale without instutional support.

 - 


* IPFS

  - [[https://en.wikipedia.org/wiki/InterPlanetary_File_System][InterPlanetary File System]] | Wikipedia
  - [[https://ipfs.io/][IPFS is the Distributed Web]] | Home
  - [[https://medium.com/@ConsenSys/an-introduction-to-ipfs-9bba4860abd0][An Introduction to IPFS]] | ConsenSys |  Medium (2016)

IPFS is giving us a distributed web, the same web we have
today but distributed.  That's good, but only a small part
of the problem we need to address.  That said, it likely is
an important part of the solution for the immediate web or
working web  -- it solves the problem I talk of, of moving
content whee people are accessing it.

at the core of this problem is location based addressing
ipfs helps solve this

"we're armoring the wire, not the data" --> find quote

* Docker

 - [[bib:goasquen:2015docker][Docker Cookbook]] | Sébastien Goasguen (2015)
 - [[bib:hane:2015build][Build Your Own PaaS with Docker]] | Hane (2015)

* Classification Of Networks

- [[https://en.wikipedia.org/wiki/Paul_Baran][Paul Baran]] | Wikipedia
- [[http://www.rand.org/content/dam/rand/pubs/research_memoranda/2006/RM3420.pdf][On Distributed Communications: I. Introduction to Distributed Communications Networks - RM3420.pdf]]


* GT.M

#+begin_comment
Interested in the idea of using GT.M for the aggregate saltmine graph
database...
#+end_comment

  - [[http://www.mgateway.com/docs/universalNoSQL.pdf]["A Universal NoSQL Engine, Using a Tried and Tested
    Technology"]] | Tweed, Rob; James, George (2010) 
  - [[https://en.wikipedia.org/wiki/GT.M][GT.M]] | Wikipedia
  - [[http://www.fisglobal.com/solutions/Banking%20and%20Wealth/Services/Database%20Engine][GT.M Database]] | FIS
  - [[https://sourceforge.net/projects/fis-gtm/][GT.M High end TP database engine download]] | SourceForge.net

  - [[https://github.com/CoherentLogic/lorikeem][CoherentLogic/lorikeem]] | LorikeeM MUMPS Developer Tools for GNU Emacs

#+begin_src sh
sudo apt-get install fis-gtm
#+end_src

* Blockchain

 - [[https://www.igvita.com/2014/05/05/minimum-viable-block-chain/][Minimum Viable Block Chain]] - igvita.com
 - [[http://johnmathews.eu/blockchain-introduction.html][Blockchains from the ground up: Part 1]] | John Mathews
 - [[https://anders.com/blockchain/][Blockchain Demo]] | video
 - [[https://github.com/anders94/blockchain-demo/][anders94/blockchain-demo]] | GitHub


* Kinto Container Services

 - [[https://devops.profitbricks.com/tutorials/deploy-a-multi-node-kubernetes-cluster-on-centos-7/][Deploy a Multi-node Kubernetes Cluster on CentOS 7]] | ProfitBricks DevOps Central
 - [[https://datasterix.com/2016/09/03/spark-cluster-using-multi-node-kubernetes-and-docker/][Spark Cluster using Multi-Node Kubernetes and Docker]] | Big is Small
 - [[https://technologyconversations.com/2015/11/04/docker-clustering-tools-compared-kubernetes-vs-docker-swarm/][Docker Clustering Tools Compared: Kubernetes vs Docker Swarm]] | Technology Conversations
 - [[https://kubernetes.io/][Kubernetes]] | Production-Grade Container Orchestration
 - [[https://www.youtube.com/watch?v=6XGUTu3WhBw][KubeCon "Migrating from homegrown ‘cluster’ to Kubernetes]] | YouTube
 - [[https://deis.com/workflow/][Deis Workflow]] | Open Source Kubernetes PaaS

   wikimedia labs & tool labs
 - http://tools.wmflabs.org/hay/directory/
 - 

 - Kubernetes Cluster
 - Flannel

The Pivot:

Dump openstack, replace with k8s, flannel and something like
Dies Workflow.

Set up like Wikimedia Labs -- give away containers to
schools, ngos, developers, students.

Get sponsorship -- sponsor a clump -- docker container group
(is that a pod?) -- schools have to sponsor their pods, and
we open up more clumps as we get sponsorship....

includes bandwidth, ip addresses, hardware, electricity, team.

set up as sg charity -- legal & banking & board

heavily push ipfs for everything....

we then propose research projects, rennovate three units
and set up vis-center

we push to get salaries for ruben and i and use half of them
to pay people back what we borrowed -- not what was invested...

* weave wikipedia articles into local content

every wikipedia article will be an ipfs literate-epub
(html, css, source, scolia, glosses, index)

you grab a copy -- and it installs in your hoard, but each
file is in ipfs and index has hash that verifies what was
used to index it.

so when you cite a wikipedia article, the image version you
cite is bundled with your paper -- eventually all papers and
books will be the same....

and images in articles will also bundle the page for that
media file -- this makes it possible to crop, or process
images and they will retain their provenance.

but because it's ipfs, it's not just a web site, it becomes
part of your file system.  this is where literate computing
and devops come in....

eventually you should be able to use this system to edit
existing and create new articles, both public and private...
