#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Research Themes Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/theme-intro.org
  :Created: 2017-04-27T16:43@Prek Leap (11.642600N-104.919210W)
  :ID: 464cfe26-769a-43e9-b980-9a2f25f72de9
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Chenla breaks work into broad themes which represent research groups
that will have any number of associated interconnected sub-themes and
deliverables including: projects, code, designs, demos, prototypes,
products, seminars, publications, media, experiments, joint-ventures,
and spinoffs associated with them.

The initial group of research themes that will launch Chenla include:

  - Process Guilds 
  - Facts & Fnords 
  - Externalized: Mind, Muscle & Memory 
  - Identity: Roles & Personas 
  - Intentional Ecosystems

* Process Guilds 
[see main page]

Networked AIs and Robots will replace nearly all human
computers and robots.

It will consolidate the assembly line, transactions,
transportation, modal shipping into a largely autonomous
network that will make small production, shortest-hop
supply, production, maintainence, and recycling.

The result will be a system that is far more flexible, and
efficient than centralised mass production.  It also has the
/potential/ of providing good, stable long term jobs and
quality of life for people in places that are nice to live
in.

I emphasize potential, because this type of a network is, as
Kevin Kelly might say, inevitable, but the form that it will
take is not.  There will be people trying to game the
system, consolidate power and wealth.  There will be
pushback from nation-states and institutions.

But /if all did go right/, it could be a very nice future.

* Facts & Fnords 
[see main page]

* Externalization: Mind, Muscle & Memory 
[see main page]

* Identity: Roles & Personas 
[see main page]

* Intentional Ecosystems
[see main page]

