#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Research Themes Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/theme-intro.org
  :Created: 2017-04-27T16:43@Prek Leap (11.642600N-104.919210W)
  :ID: 464cfe26-769a-43e9-b980-9a2f25f72de9
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Chenla breaks work into broad themes which represent research groups
that will have any number of associated interconnected sub-themes and
deliverables including: projects, code, designs, demos, prototypes,
products, seminars, publications, media, experiments, joint-ventures,
and spinoffs associated with them.

The initial group of research themes that will launch Chenla include:

  - Process Guilds 
  - Facts & Fnords 
  - Externalized: Mind, Muscle & Memory 
  - Identity: Roles & Personas 
  - Intentional Ecosystems

* Process Guilds 
[see main page]

** Background

Technological revolutions that have reshaped human civilization, are
characterized by the introduction of technologies and methodologies
that transform by breaking up centralized concentrated power
structures and moving everything from power, production, education,
wealth etc from a small entrenched elite to the edges.  The invention
of spoken language, the cultivation and domestication of plants and
animals, the invention of writing systems, Gutenberg's Press, the
Industrial Revolution and the combined Computer-Network Revolution all
decentralized existing power structures.

And even before the Computer-Network Revolution has even reached its
zenith, it is incubating and making possible the next revolution that
is nearly apon us; Artificial Intelligence-Robotics.

Globalization was born from a number of different pieces including
Henry Ford's factory assembly line, standardization of a wide variety
of parts from screws and nuts, to electrical plugs, batteries, light
bulbs etc, the global adoption of cargo pallets combined with modal
shipping containers (ubiquitious twenty and forty foot corrugated
steel boxes).  But it was the standardization and interoperability of
telephone communications that made it possible to punch a number into
a box on your table and connect to any other telephone on the planet.
This paved the way for dedicated computer networks which were also
globally interoperable.  This quickly globalized first communication,
then the spread of news and information and just as importantly
globalized the transfer and exchange of money and transformed symbolic
fiat currencies stamped out into metal coins, and printed on paper
bank promisary notes into pure information.  Money has become pure
information that is not backed up by paper notes, or precious metals.

Globalization, if looking at any number of metrics has been an
enormous success [ list successes ]

However, and this is a significant however, Globalization is only
benificial at scale.  And the scale, in many respects comes down to a
single set of numbers; 40'x8'x8'6" (imperial), the size of a standard
ISO Shipping Container.  Producers who can deliver goods in multiples
of these dimensions win.  Most smaller producers don't and have been
pushed out of the market and out of business unless they can become
sub-suppliers for aggregators who will take their cut in the middle.

A second characteristic of Globalization was inherited from the
Industrialization; mass production of identical goods.  If a market
wasn't big enough to justify producing many containers worth of copies
of the same goods, then it gradually stopped being produced.

The result of all of this scaling is that mass production and
globalized transporation, logistics, communications and flow of money
could produce far more goods than people actually need.  This trend
had begun at the beginning of the 20th century, and gradually became
the norm rather than the exception.  Producers made more goods than
they could sell.  So enormous amounts of resources went into
converting a production system that met peoples needs, to a lifestyle
consumer system that met people's wants.  Even this wasn't enough, so
products were purposely designed to only last anywhere from 1-3 years
and then fail so that they would have to be replaced by whatever
people felt they desired.

** Impact of Palletization and Containerization

Basically it cut out, middlemen by making the transfer of goods from
one form of transport to another very efficient -- before pallets and
containers, goods were loaded directly into trucks and ships.  This
required enormous amount of labour and time, as small armies moved
goods into nets or carried boxes and other containers by hand and
restacked them in in a ship for the next leg of the journey.  In
addition to labor and time, there was high amount of breakage and
theft, as goods "fell off the back of a truck" and vanished into gray
markets and shadow economies.  Loading and unloading a ship could not
be done in hours, not over many days.  Dock workers were a very
powerful labor block that were sometimes controlled by unions
controlled by corrupt officials and organized crime.


