
#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Chenla Research Themes Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/projects/theme-intro.org
:Created:   2017-04-27T16:43@Prek Leap (11.642600N-104.919210W)
:ID:        464cfe26-769a-43e9-b980-9a2f25f72de9
:VER:       551911853.835402225
:GEO:       48P-491193-1287029-15
:BXID:      proj:HWK4-6466
:Class:     project
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-project-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Chenla breaks work into broad themes which represent
research groups that will have any number of associated
interconnected sub-themes and deliverables including:
projects, code, designs, demos, prototypes, products,
seminars, publications, media, experiments, joint-ventures,
and spinoffs associated with them.

The initial group of research themes that will launch Chenla
include:

  - Process Guilds 
  - Facts & Fnords 
  - Externalized: Mind, Muscle & Memory 
  - Identity: Roles & Personas 
  - Intentional Ecosystems

* Process Guilds 
[see main page]

Networked AIs and Robots will replace nearly all human
computers and robots.

It will consolidate the assembly line, transactions,
transportation, modal shipping into a largely autonomous
distributed, federated network that will make small
production, shortest-hop supply, production, maintainence,
and recycling.

The result will be a system that is far more flexible, and
efficient than centralised mass production.  It also has the
/potential/ of providing good, stable long term jobs and
quality of life for people in places that are nice to live
in.

In a world without human computers and robots, the concept
of blue and white collar work will largely disappear.  The
middle class emerged from the merchant class who were the
first middlemen in the early days of the industrial
revolution.  The ai-robotic revolution could potentially
flatten existing class distinctions.

I emphasize /potential/, because this type of a network is, as
Kevin Kelly might say, inevitable, but the form that it will
take is not.  There will be people trying to game the
system, consolidate power and wealth.  There will be
pushback from nation-states and institutions.

The Process Guild Research Group will introduce and explore
a number of novel new approaches for building such networks
and introduce some odd new names such as the Sneakernet of
Things (SNOT), it-torrents, and micro intermodal transport.


* Facts & Fnords 
[see main page]

Human societies run on the identification, testing,
confirming and exchange of facts.  In a broader sense every
living thing does the same thing.  We try to figure out what
is happening, determine the probability of it being true or
not and then making a decision.  If you get the fact that
there is a saber tooth tiger in the bushes ahead of you
wrong, you are dead.

But before something becomes a fact, that has been
determined to be true, there are many assertions that are
made that when tested may be true, may be false, may be
intentionally false (aka a lie) as well as estimating the
probability of something being true or not.  If something is
true but has a very low probability we treat it differently
from what is more likely to happen.  We call the sum total
of all possible causal states for an assertion a /fnord/.
Every assertion has is a fnord until it has been observed
and evaluated and then beomes fact, fiction, truth lie etc.

The Internet has flooded us with assertions, but hasn't yet
provided a means of determining what is true and false,
probable and improbable.

The Fact & Fnord Research Group will explore how to solve
this problem and develop infrastructure and platforms that
can be used in potentially every facet of personal, civic,
commercial, and social act we take in life.  Again, there
will be some odd new concepts that we will be introducing
including holons, duck tests, canary tests, cascading rule
sets and graph databases that will be used to build
infrastructure and platforms that can be deployed as
services and products.

* Externalized: Mind, Muscle & Memory 
[see main page]




* Identity: Roles & Personas 
[see main page]

Social media networks see users as what Mark Zukerberg
calls, /the social graph/.  The social graph essentially
takes Google's insight about ranking pages according to how
other pages link to that page, and applied it to people and
the connections they have with other people.

What it misses (and this is something big enough to drive a
jumbo jet through) is that this is not how people are
connected to each other.

Personal identity is complex and still not wholly
understood.  None of us are one person, we are many
different people, each playing a different overlapping role,
with links to different people, with different levels of
authority, wealth, credit, self-image and even
personalities.

We all play different roles, as friends, lovers, spouses,
parents, children, siblings, citizens, employees, alumni,
church or union or country-club member.  But social media
tends to mash them all together in ways that cause all sorts
of problems in our lives.  It's increasingly said that
facebook makes you hate people.  That's because social media
bleeds information from different roles ad personas in our
lives to people who are not part of those roles.

The problem is broader than social media.  It extends to
your role as an employee or student when things that you
have done or said that have nothing to do with your school
or company come to their attention and they feel that they
have a right to tell you what you can and can not do.  This
is now a problem when you are going through border control,
trying to rent an apartment, or get a mortgage, or even take
your children to the neighborhood playground.  All of the
walls we keep between roles that allow us to live normal
lives have all been torn down.

The Roles & Personas Research Group will explore solutions
to these problems and develop methodologies, standards and
code that can help return common sense privacy to our lives.

* Intentional Ecosystems
[see main page]


  - managed wilderness
  - farms (forest, savvanah, and pond)
  - biospheres


@in
