#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Tools Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/projects/tools-intro.org
:Created:   2017-05-05T18:10@Prek Leap (11.642600N-104.919210W)
:ID:        fa8137bb-ce2d-4300-ace9-0ce060e469f4
:VER:       551912026.899985224
:GEO:       48P-491193-1287029-15
:BXID:      proj:NGG8-1113
:Class:     project
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-project-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction


 - [[http://www.wholeearth.com/issue/1220/article/280/one.highly.evolved.toolbox][One Highly Evolved Toolbox]] | Whole Earth Catalog

/The Whole Earth Catalog/ : Access to Tools and its
grandchild Kevin Kelly's /Cool Tools/ are fantastic, but we
need something a bit more comprehensive, and authoritative
as a long term tool reference -- I'm not talking about a
history, or an encyclopedia -- but to get to the essence of
what each tool is, history, how to make, how to use, and
precise instructions and designs in how to make....

This is right up the Long Now's alley, as well as Cool
Tools, but also Dartnell's crowd.  The idea is that if an
asteroid wipes us out, and people find these books, the
first will be a primer that will show how to recycle
existing materials but also how to mine and turn it all into
steel and eventually the tools needed to build first an
agricultural and then industrial civilization.

You can do a hell of a lot with a bit of flint, a hoe,
dibble, axe, and knife.

#+begin_comment
what was the movie about the barang crashing his plane in
the arctic with a native woman -- who builds everything to
survive and travel from scratch....

the arctic illegible to him, but perfectly legible to her.
#+end_comment
      

But it won't start out that way -- it will start out as an
inventory of the essential tools needed for working with
wood, metal, agriculture, animal husbandry, fishing.  And
then move on to tools for working with and making machines.

It will have to cover things that the tools are meant to
work with -- so nails, screws, hinges etc are important.
Tools for creating and working with iron and steel.
Welding.  How to make charcoal, and a blast furnace.  How to
build a foundry, and make everything from candles, to lamps,
coolers, cookers, wheelbarrows, carts, boats etc.....

And we will ensure that this will work in different
bioregions at different levels of complexity -- Mad Max,
neo-Edwardian, Bladerunner.  And in different atmospheres, a
vacuum and different levels of gravity.  So this toolset (or
at least a subset of it) should be just as useful on ISS,
the moon, mars or in the belt.

* anti-blueprint 


We need a different way of teaching and thinking about
tools.

CAD and plans should not be verbotten -- they should provide
ranges that can then be tailored for different uses -- a
master will have different requirements of a hammer than
someone living in a flat, or a student at school.  Different
size and weight and balance -- 

#+begin_quote
Let us say that blueprints were made for these two lamps,
and sent out to technicians, who were able to able to read
the drawings, and had the neccesary skills to make the lamps
according to the blueprints.  Unfortunately, though the
blueprint itself gives no information about themselves, how
useful they are, or whether that work well or badly.  The
blueprint in no way establishes the likely use, or the
likely behavior of these two lamps.... The design, /in the
form of a blueprint/, tells people nothing significant about
the relative quality or value  or usefulness of the two
lamps.

-- Battle pg53
#+end_quote


In a very real sense, you can't separate a tool from what it
is used for....  and tools are used to make tools....

The WEC and Cool Tools make assumptions about what people
know about tools -- many of these are cultural assumptions


** In the Beginning Was The Command Line

section about tools used by masters....


** Roubo's polissoir
  
  - [[http://trestore.wkfinetools.com/finish-wood/Polissoir/Polissoir-01.asp][The Polissoir - a Tool You’ve (Probably) Never Heard
     of]] | by Chris Schwarz

  - [[https://en.wikipedia.org/wiki/Andr%C3%A9_Jacob_Roubo][André Jacob Roubo]] | Wikipedia
  - [[https://archive.org/details/gri_33125009321916][L'art du menuisier : Roubo, M. (André Jacob),
    1739-1791]] vol2 | Internet Archive
  - https://archive.org/search.php?query=L%27art%20du%20menuisier 
    4 volumes


#+begin_quote
Roubo’s work is a massive work that was issued in three
magnificent folios and discussed veneer, furniture-making,
marquetry, carriage building, garden furniture and much
more.

And though Roubo covers a lot of ground, he also assumes the
reader knows a lot about the subject of woodworking, and so
some things are not covered in deep detail and you need to
tease out the information you need by reading about the tool
or technique when it comes up in other parts of the books.

This is true of the polissoir.  Here is all that Roubo wrote
in describing the polissoir in plate 296:

    “The polisher, figures 8 & 9, is a sheaf of ordinary
    grass or straw, about 4 thumbs long, by about 2 thumbs
    in diameter. This sheaf is bound tightly along its
    length. Before making use of it, one soaks it in molten
    wax, which one lets cool, after which one rubs the
    polish on a piece of wood to smooth it and make it
    proper to polish the work.

    There are polishers of diverse forms and sizes, in order
    to be able to get into all parts, nooks and crannies.”

-- [[http://trestore.wkfinetools.com/finish-wood/Polissoir/Polissoir-01.asp][The Polissoir - a Tool You’ve (Probably) Never Heard
   of]] | by Chris Schwarz
#+end_quote

** Japanese knife maker


Add story about old japanese knife maker who required that
each customer submit a letter describibg how they will use
the knife....
