#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Tools Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/projects/tools-intro.org
  :Created: 2017-05-05T18:10@Prek Leap (11.642600N-104.919210W)
  :ID: fa8137bb-ce2d-4300-ace9-0ce060e469f4
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

/The Whole Earth Catalog/ : Access to Tools and its
grandchild Kevin Kelly's /Cool Tools/ are fantastic, but we
need something a bit more comprehensive, and authoritative
as a long term tool reference -- I'm not talking about a
history, or an encyclopedia -- but to get to the essence of
what each tool is, history, how to make, how to use, and
precise instructions and designs in how to make....

This is right up the Long Now's alley, as well as Cool
Tools, but also Dartnell's crowd.  The idea is that if an
asteroid wipes us out, and people find these books, the
first will be a primer that will show how to recycle
existing materials but also how to mine and turn it all into
steel and eventually the tools needed to build first an
agricultural and then industrial civilization.

You can do a hell of a lot with a bit of flint, a hoe,
dibble, axe, and knife.

#+begin_comment
what was the movie about the barang crashing his plane in
the arctic with a native woman -- who builds everything to
survive and travel from scratch....

the arctic illegible to him, but perfectly legible to her.
#+end_comment
      

But it won't start out that way -- it will start out as an
inventory of the essential tools needed for working with
wood, metal, agriculture, animal husbandry, fishing.  And
then move on to tools for working with and making machines.

It will have to cover things that the tools are meant to
work with -- so nails, screws, hinges etc are important.
Tools for creating and working with iron and steel.
Welding.  How to make charcoal, and a blast furnace.  How to
build a foundry, and make everything from candles, to lamps,

And we will ensure that this will work in different
bioregions at different levels of complexity -- Mad Max,
neo-Edwardian, Bladerunner.  And in different atmospheres, a
vacuum and different levels of gravity.  So this toolset (or
at least a subset of it) should be just as useful on ISS,
the moon, mars or in the belt.
